name: Webhook Trigger

on:
  repository_dispatch:
    types: [jira_webhook]

jobs:
  handle-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Process Webhook Payload
        run: |
          echo "Issue Key: ${{ github.event.client_payload.issue.key }}"
          echo "Summary: ${{ github.event.client_payload.issue.fields.summary }}"
          echo "Status: ${{ github.event.client_payload.issue.fields.status.name }}"
          echo "Assignee: ${{ github.event.client_payload.issue.fields.assignee.displayName }}"
          echo "Due Date: ${{ github.event.client_payload.issue.fields.duedate }}"

