name: Webhook Trigger

on:
  repository_dispatch:
    types: 
      - jira:issue_updated

jobs:
  handle-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Log Webhook Payload
        run: echo "Webhook payload:${{ toJson(github.event.client_payload) }}"
