name: Webhook Trigger

on:
  repository_dispatch:

jobs:
  handle-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Log Webhook Payload
        run: |
          echo "Webhook payload: ${{ toJson(github.event.client_payload) }}"
          echo "Issue Key: ${{ github.event.client_payload.issue_key }}"
          echo "Summary: ${{ github.event.client_payload.summary }}"
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Assignee: ${{ github.event.client_payload.assignee }}"
          echo "Due Date: ${{ github.event.client_payload.due_date }}"
