name: Webhook Trigger

on:
  repository_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Webhook Data
        run: |
          echo "Webhook data received: ${{ toJson(github.event.client_payload) }}"
      
      - name: Send notification to MS Teams
        run: |
          curl -H "Content-Type: application/json" -d '{
            "text": "**Issue Summary:** '${{ github.event.client_payload.issue.fields.summary }}' \n**Assigned Developer:** '${{ github.event.client_payload.issue.fields.assignee.displayName }}' \n**Due Date:** '${{ github.event.client_payload.issue.fields.duedate }}' \n**Status:** '${{ github.event.client_payload.issue.fields.status.name }}' \n[View Issue](https://your-jira-instance/browse/${{ github.event.client_payload.issue.key }})"
          }'  https://avaxia.webhook.office.com/webhookb2/aa5a370b-ad1a-4c10-b494-e15d9490f751@7ecf1dcb-eca3-4727-8201-49cf4c94b669/IncomingWebhook/77dc558b4d66402db52b304ce78097e7/c4682019-2eb9-4850-9ea4-d512675d55bb/V2Pd7iajBd6SYzb33ivoOoma3Tds6gdz6Eh0mRcUvO2UU1
