name: Jira Notification Workflow

on:
  repository_dispatch:
    types: [jira_webhook]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Debug Webhook Data
      - name: Debug Webhook Data
        run: |
          echo "Webhook data received: ${{ toJson(github.event.client_payload) }}"

      # Step 2: Debug Individual Fields
      - name: Debug Individual Fields
        run: |
          echo "Issue Summary: '${{ github.event.client_payload.issue.fields.summary }}'"
          echo "Assigned Developer: '${{ github.event.client_payload.issue.fields.assignee.displayName }}'"
          echo "Due Date: '${{ github.event.client_payload.issue.fields.duedate }}'"
          echo "Status: '${{ github.event.client_payload.issue.fields.status.name }}'"

      # Step 3: Send Notification to MS Teams
      - name: Send Notification to MS Teams
        run: |
          # Extract fields from the webhook payload and escape quotes
          ISSUE_SUMMARY=$(echo "${{ github.event.client_payload.issue.fields.summary }}" | sed 's/"/\\"/g')
          ASSIGNEE=$(echo "${{ github.event.client_payload.issue.fields.assignee.displayName }}" | sed 's/"/\\"/g')
          DUE_DATE=$(echo "${{ github.event.client_payload.issue.fields.duedate }}" | sed 's/"/\\"/g')
          STATUS=$(echo "${{ github.event.client_payload.issue.fields.status.name }}" | sed 's/"/\\"/g')

          # Debug the values to confirm they are correctly set
          echo "Issue Summary: '$ISSUE_SUMMARY'"
          echo "Assigned Developer: '$ASSIGNEE'"
          echo "Due Date: '$DUE_DATE'"
          echo "Status: '$STATUS'"

          # Construct the JSON payload with proper line breaks
          JSON_PAYLOAD=$(cat <<EOF
          {
            "text": "**Issue Summary:** $ISSUE_SUMMARY \\n**Assigned Developer:** $ASSIGNEE \\n**Due Date:** $DUE_DATE \\n**Status:** $STATUS \\n[View Issue](https://mohamedalizaidi48.atlassian.net/browse/${{ github.event.client_payload.issue.key }})"
          }
            EOF
          )

          # Debug the constructed JSON payload
          echo "JSON Payload: $JSON_PAYLOAD"

          # Send the notification to MS Teams
          curl -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://avaxia.webhook.office.com/webhookb2/aa5a370b-ad1a-4c10-b494-e15d9490f751@7ecf1dcb-eca3-4727-8201-49cf4c94b669/IncomingWebhook/77dc558b4d66402db52b304ce78097e7/c4682019-2eb9-4850-9ea4-d512675d55bb/V2Pd7iajBd6SYzb33ivoOoma3Tds6gdz6Eh0mRcUvO2UU1
