name: Handle Approval Workflow

on:
  repository_dispatch:
    types: [approve, reject]

jobs:
  handle_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Approval or Rejection
        run: |
          ISSUE_KEY="${{ github.event.issueKey }}"
          ACTION="${{ github.event.action }}"
          echo "$ACTION"
          if [ "$ACTION" == "approve" ]; then
            echo "Updating Jira issue $ISSUE_KEY to Approved"
            TRANSITION_ID="3"
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Basic bW9oYW1lZGFsaXphaWRpNDhAZ21haWwuY29tOkFUQVRUM3hGZkdGMElreVJBQVhHWkJVaU94MTJpMmVidE5tbDlZY3ZqVU1ySjIwaXdBX1FfTDlzYzBodDVwRmkyLTM4RWptakpGclhBT0ZqSUNMSHpaOGw0Mzdyb0d5Q3BZU2dRX2Y4SFRlN05sSm52d18xOERSMmFULWdqV3RDTW1lUm5NTUlfVVhkc2E2LWlheTdPYldRd3R3c0VvM1d1LWluSjRPUk12OUxHTjVSYmU5dGZ1az1GQjAzODUwNw== \
              --data "{\"transition\": {\"id\": \"$TRANSITION_ID\"}}" \
              "https://your-domain.atlassian.net/rest/api/2/issue/SCRUM-8/transitions"
          elif [ "$ACTION" == "reject" ]; then
            echo "Updating Jira issue $ISSUE_KEY to Rejected"
            TRANSITION_ID="2"
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Basic bW9oYW1lZGFsaXphaWRpNDhAZ21haWwuY29tOkFUQVRUM3hGZkdGMElreVJBQVhHWkJVaU94MTJpMmVidE5tbDlZY3ZqVU1ySjIwaXdBX1FfTDlzYzBodDVwRmkyLTM4RWptakpGclhBT0ZqSUNMSHpaOGw0Mzdyb0d5Q3BZU2dRX2Y4SFRlN05sSm52d18xOERSMmFULWdqV3RDTW1lUm5NTUlfVVhkc2E2LWlheTdPYldRd3R3c0VvM1d1LWluSjRPUk12OUxHTjVSYmU5dGZ1az1GQjAzODUwNw== \
              --data "{\"transition\": {\"id\": \"$TRANSITION_ID\"}}" \
              "https://your-domain.atlassian.net/rest/api/2/issue/SCRUM-8/transitions"
          fi
          #d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
