name: Handle Approval Workflow

on:
  repository_dispatch:
    types: [approve, reject]

jobs:
  handle_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Approval or Rejection
        run: |
          ISSUE_KEY="${{ github.event.client_payload.issueKey }}"
          ACTION="${{ github.event.action }}"
          
          if [ "$ACTION" == "approve" ]; then
            echo "Updating Jira issue $ISSUE_KEY to Approved"
            curl -X PUT -H "Content-Type: application/json" \
            -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
            --data '{"fields": {"status": {"name": "Approved"}}}' \
            https://mohamedalizaidi48.atlassian.net/rest/api/2/issue/$ISSUE_KEY
          elif [ "$ACTION" == "reject" ]; then
            echo "Updating Jira issue $ISSUE_KEY to Rejected"
            curl -X PUT -H "Content-Type: application/json" \
            -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
            --data '{"fields": {"status": {"name": "Rejected"}}}' \
            https://mohamedalizaidi48.atlassian.net/rest/api/2/issue/$ISSUE_KEY
          fi
          #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
